### ISSUE TITLE
BaseCampWorkerMaxNum isn't working

### ISSUE THREAD

**Issue by ow1337** [DysonCheng/PalWorldSettingGenerator#1]
So i tested out the PalWorldSettingsGenerator, and ofc i couldn't test all, but some stuff seems to work, some not, so i can't change the BaseCampWorkerMaxNum, its always capped to 15.

**Comment by DysonCheng** [comment]
The BaseCampWorkerMaxNum not work for now. In my estimation, the phenomenon seems to be limited by the client page. :)
